#ifndef PROJECT_CANDLESTICK_CHART_CANDLESFWD_H
#define PROJECT_CANDLESTICK_CHART_CANDLESFWD_H
class Model;
class load;
class MainDialog;
class chartwindow;

#endif //PROJECT_CANDLESTICK_CHART_CANDLESFWD_H
